# Generated by Django 5.2 on 2025-06-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_created_story_created_at_postfilecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['-date']},
        ),
    ]
