# Generated by Django 4.2 on 2025-06-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_profile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_active',
        ),
    ]
