# Generated by Django 5.2 on 2025-06-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_remove_profile_is_online_remove_profile_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_by', to='authy.profile'),
        ),
    ]
