# Generated by Django 5.2 on 2025-06-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
