# Generated by Django 5.2 on 2025-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_remove_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='authy.profile'),
        ),
    ]
